--!strict
-- WaterSwimClient (retired)
-- Swimming is now handled natively by Roblox Terrain water filled beneath the
-- visual water plane. The Humanoid enters the Swimming state on its own, which
-- drives the swim animation and water sounds with correct physics and controls.
